services:

  db:
    image: postgres:15
    container_name: ticket_db
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: ticket_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      GOOGLE_API_KEY: AIzaSyB6q421W2INvTVNd5PCLboaa9pwh_vWvTk
      DB_NAME: tickets
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    command: >
      sh -c "
      until nc -z db 5432;
      do
        echo 'Waiting for database...';
        sleep 2;
      done;
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
